providers:
  - amazon
  - amazonprimevideo
  - amazonprimevideowithads
  - disneyplus
  - netflix
  - nowonline
  - nowtv
  - o2tvcz
  - orange
  - pathe
  - peacocktv
  - play
  - premierycanalplus
  - sfanytime
  - showmax
  - skygo
  - skyshowtime
  - skystore
  - skyticket
  - spectrumondemand
  - sumotv2
  - swisscom
  - telstratv
  - universcine
  - viaplay
  - videoload
  - vudu
  - wavve
  - wuaki
  - youtube
  - zee5
