# comment out providers you don't own, list may be non-exhaustive
providers:
  - amazon
  - amazonprime
  - amazonprimevideo
  - amazonprimevideowithads
  - atomtickets
  - bbtheatres
  - catchplay
  - cineplex
  - cinepoliscinema
  - clarovideo
  - disneyplus
  - entertaintv
  - fandango
  - filminplus
  - flixfling
  - go3
  - hungamaplay
  - itunes
  - jiocinema
  - kpn
  - max
  - maxdomestore
  - mediasetplay
  - mejane
  - microsoft
  - movistar
  - naverstore
  - neontvnz
  - netflix
  - nowonline
  - nowtv
  - o2tvcz
  - orange
  - pathe
  - peacocktv
  - play
  - premierycanalplus
  - sfanytime
  - showmax
  - skygo
  - skyshowtime
  - skystore
  - skyticket
  - spectrumondemand
  - sumotv2
  - swisscom
  - telstratv
  - universcine
  - viaplay
  - videoload
  - vudu
  - wavve
  - wuaki
  - youtube
  - zee5
country: "US" # Determines only in which conutry the initial search is performed
language: "en" # Your preferred language
result_count: 4 # Determines how many results are shown on result page
host: "0.0.0.0"